{
  "hash": "fde3f5688cd845dfe0fc07ed9c28b8e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelling fish weights with multiple predictors\"\ncategories: \n  - Application exercise\n  - Sugested answers\neditor: visual\neditor_options: \n  chunk_output_type: console\nformat: \n  html:\n    fig-width: 6\n    fig-asp: 0.618\n---\n\n\nFor this application exercise, we will continue to work with data on fish. The dataset we will use, called `fish`, is on two common fish species in fish market sales. We're going to investigate the relationship between the weights and heights of fish, and later take into consider species as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n\nfish <- read_csv(\"data/fish.csv\")\n```\n:::\n\n\nThe data dictionary is below:\n\n| **variable**      | **description**        |\n|-------------------|------------------------|\n| `species`         | Species name of fish   |\n| `weight`          | Weight, in grams       |\n| `length_vertical` | Vertical length, in cm |\n| `length_diagonal` | Diagonal length, in cm |\n| `length_cross`    | Cross length, in cm    |\n| `height`          | Height, in cm          |\n| `width`           | Diagonal width, in cm  |\n\n# Interpreting multiple regression models\n\nIn the previous application exercise you saw that the model predicting weight from height and species was a better fit. In this section we will interpret the coefficients of this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfish_whs_fit <- linear_reg() |>\n  fit(weight ~ height + species, data = fish)\n\ntidy(fish_whs_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -828.      69.7     -11.9  1.92e-16\n2 height           95.2      4.54     21.0  5.10e-27\n3 speciesRoach    343.      41.8       8.19 6.35e-11\n```\n\n\n:::\n:::\n\n\n-   What does each row in the model output represent?\n\n*The first row is the intercept. The second row is the slope for `height`. The third row is the slope for `speciesRoach`. In this case the other species level, Bream, is the reference level.*\n\n-   Interpret the intercept and the slopes.\n\n    -   *Intercept, -828: Bream fish that are 0 cm in height are expected to weigh, on average -828 grams. This value doesn't make sense in context of the data.*\n\n    -   *height, 95.2: All else held constant, for each cm the height of fish is higher, weights of fish are expected, on average, to be higher by 95.2 grams.*\n\n    -   *speciesRoach, 343: All else held constant, Roach fish are expected, on averge to weigh 343 grams more than Bream fish, on average.*\n\n-   Write the model.\n\n$$\n\\widehat{weight} = -828 + 95.2 \\times height + 343 \\times speciesRoach\n$$\n\n# Additive vs. interaction models\n\n-   Run the two code chunks below and create two separate plots. How are the two plots different than each other? Which plot does the model we fit above represent?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(fish, aes(x = height, y = weight, color = species)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Plot A - Interaction model\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-10-more-fish-sa_files/figure-html/model-a-1.png){width=576}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfish_whs_aug <- augment(fish_whs_fit, new_data = fish)\n\nggplot(\n  fish_whs_aug, \n  aes(x = height, y = weight, color = species)\n  ) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(aes(y = .pred), method = \"lm\") +\n  labs(title = \"Plot B - Additive model\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-10-more-fish-sa_files/figure-html/model-b-1.png){width=576}\n:::\n:::\n\n\n-   Look back at Plot B. What assumption does the additive model make about the slopes between flipper length and body mass for each of the three islands?\n\n*The additive model assumes the same slope between height and weight of fish for the two species.*\n\n# Choosing models\n\nRule of thumb: **Occam's Razor** - Don't overcomplicate the situation! We prefer the *simplest* best model.\n\n-   Choose a model using this principle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# interaction\n\nfish_whs_int_fit <- linear_reg() |>\n  fit(weight ~ height * species, data = fish)\n\ntidy(fish_whs_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                estimate std.error statistic  p.value\n  <chr>                  <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)           -942.      68.6     -13.7  9.20e-19\n2 height                 103.       4.48     22.9  1.61e-28\n3 speciesRoach           673.      93.5       7.20 2.64e- 9\n4 height:speciesRoach    -39.9     10.4      -3.85 3.30e- 4\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(fish_whs_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.969         0.968  51.3      540. 1.31e-38     3  -293.  595.  605.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n\n```{.r .cell-code}\n# additive\n\nfish_whs_fit <- linear_reg() |>\n  fit(weight ~ height + species, data = fish)\n\ntidy(fish_whs_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -828.      69.7     -11.9  1.92e-16\n2 height           95.2      4.54     21.0  5.10e-27\n3 speciesRoach    343.      41.8       8.19 6.35e-11\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(fish_whs_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.961         0.959  57.7      634. 3.07e-37     2  -300.  607.  615.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n*Choose the interaction model since it has a higher adjusted R-squared.*\n\n-   What is R-squared? What is adjusted R-squared?\n\n*R-squared is the percent variability in the response that is explained by our model. (Can use when models have same number of variables for model selection)*\n\n*Adjusted R-squared is similar, but has a penalty for the number of variables in the model. (Should use for model selection when models have different numbers of variables).*\n",
    "supporting": [
      "ae-10-more-fish-sa_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}