---
title: "HW 3"
editor: visual
editor_options: 
  chunk_output_type: console
---

::: callout-important
This homework is due Thursday, Oct 26 at 5:00 pm ET.
:::

# Getting Started

-   Go to the [sta113-f23](https://github.com/sta113-f23) organization on GitHub. Click on the repo with the prefix `hw-3`. It contains the starter documents you need to complete the homework assignment.
-   Click on the green **CODE** button, select **Use SSH** (this might already be selected by default, and if it is, you'll see the text **Clone with SSH**). Click on the clipboard icon to copy the repo URL.
-   In RStudio, go to *File* ➛ *New Project* ➛*Version Control* ➛ *Git*.
-   Copy and paste the URL of your assignment repo into the dialog box *Repository URL*. Again, please make sure to have *SSH* highlighted under *Clone* when you copy the address.
-   Click *Create Project*, and the files from your GitHub repo will be displayed in the *Files* pane in RStudio.
-   Click *hw-3.qmd* to open the template Quarto file. This is where you will write up your code and narrative for the lab.

## Packages

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(tidymodels)
```

## Guidelines + tips {#sec-guidelines-tips}

Your plots should include an informative title, axes should be labeled, and careful consideration should be given to aesthetic choices.

Remember that continuing to develop a sound workflow for reproducible data analysis is important as you complete this homework and other assignments in this course. There will be periodic reminders in this assignment to remind you to knit, commit, and push your changes to GithHub. You should have **at least 3 commits with meaningful commit messages** by the end of the assignment.

::: callout-note
Note: Do not let R output answer the question for you unless the question specifically asks for just a plot. For example, if the question asks for the number of columns in the data set, please type out the number of columns. You are subject to lose points if you do not.
:::

## Workflow + formatting

Make sure to

-   Update author name on your document.
-   Label all code chunks informatively and concisely.
-   Follow the Tidyverse code style guidelines.
-   Make at least 3 commits.
-   Resize figures where needed, avoid tiny or huge plots.
-   Use informative title and axis labels.
-   Turn in an organized, well formatted document.

